name: Deploy Levantér

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build and deploy
        env:
          NODE_ENV: production
        run: |
          npm run build
          npm run deploy
      - name: Deploy to Vercel
        uses: vercel/vercel-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org: Reddevilelbicho
          vercel-project: levantér
          production: true
